/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package View;

import Controller.CadeiraController;
import Controller.DocenteController;
import Model.Cadeira;
import Model.Docente;
import Model.GeradorSenha;
import Model.User;
import Service.DocenteService;
import Util.Connection;
import Util.Role;
import javax.persistence.EntityManager;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Carla Morais
 */
public class ViewCadastroDocente extends javax.swing.JInternalFrame {

    private JTextField campoNome;
    private JTextField campoEspecializacao;
    private JTextField campoExperiencia;
    private JTextField campoEndereco;
    private JTextField campoTelefone;
    private JTextField campoEmail;
 


    public ViewCadastroDocente() {
        initComponents();
        preencherComboBoxNivel();

    }

    private void popularTabela() {
        DefaultTableModel modeloTabela = (DefaultTableModel) TabelaDocentes.getModel();
        DocenteController docente = new DocenteController();
        docente.exibirDocente(modeloTabela);

    }

    private void actualizarTabela() {
        popularTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCD = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        TextNome = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TextTelefone = new javax.swing.JTextField();
        TextEmail = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TextEndereco = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JToggleButton();
        jLabel5 = new javax.swing.JLabel();
        TxtEspecializacao = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        textExperiencia = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        ComboBoxCadeiras = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaDocentes = new javax.swing.JTable();
        btnExcluir = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        ComBoxNivelAcesso = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Tela Cadastro Docente");

        jPanelCD.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados Pessoais", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 18))); // NOI18N

        TextNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextNomeActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Nome");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Telefone");

        TextTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextTelefoneActionPerformed(evt);
            }
        });

        TextEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextEmailActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("E-mail");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Endereço");

        TextEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextEnderecoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(TextNome, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                    .addComponent(TextTelefone))
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(TextEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(TextEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TextEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Especialização");

        TxtEspecializacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtEspecializacaoActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Experiência");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Cadeira Lecionada");

        ComboBoxCadeiras.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                ComboBoxCadeirasAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        ComboBoxCadeiras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxCadeirasActionPerformed(evt);
            }
        });

        TabelaDocentes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Email", "Telefone", "Especialização", "Experiência", "Endereço"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TabelaDocentes.setGridColor(new java.awt.Color(204, 204, 204));
        jScrollPane1.setViewportView(TabelaDocentes);

        btnExcluir.setText("Eliminar");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel8.setText("Nível de Acesso");

        javax.swing.GroupLayout jPanelCDLayout = new javax.swing.GroupLayout(jPanelCD);
        jPanelCD.setLayout(jPanelCDLayout);
        jPanelCDLayout.setHorizontalGroup(
            jPanelCDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCDLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jPanelCDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCDLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(133, 133, 133)
                        .addComponent(jLabel7))
                    .addComponent(TxtEspecializacao, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 682, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(67, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCDLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelCDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCDLayout.createSequentialGroup()
                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(125, 125, 125))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCDLayout.createSequentialGroup()
                        .addComponent(ComboBoxCadeiras, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addGroup(jPanelCDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(textExperiencia, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(76, 76, 76))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCDLayout.createSequentialGroup()
                        .addGroup(jPanelCDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(ComBoxNivelAcesso, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35))))
        );
        jPanelCDLayout.setVerticalGroup(
            jPanelCDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCDLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ComBoxNivelAcesso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCDLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelCDLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanelCDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelCDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textExperiencia, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ComboBoxCadeiras, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtEspecializacao, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addGroup(jPanelCDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelCD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelCD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtEspecializacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtEspecializacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtEspecializacaoActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        salvarDocente();


    }//GEN-LAST:event_btnSalvarActionPerformed

    private void TextEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextEnderecoActionPerformed

    private void TextEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextEmailActionPerformed

    private void TextTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextTelefoneActionPerformed

    private void TextNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextNomeActionPerformed

    private void ComboBoxCadeirasAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_ComboBoxCadeirasAncestorAdded
        // TODO add your handling code here:
        jComboBox1AncestorAdded(evt);


    }//GEN-LAST:event_ComboBoxCadeirasAncestorAdded

    private void ComboBoxCadeirasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxCadeirasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxCadeirasActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed

        DefaultTableModel TBDocentes = (DefaultTableModel) TabelaDocentes.getModel();
        int selectedRow = TabelaDocentes.getSelectedRow();

        if (selectedRow != -1) {
            Object idObj = TBDocentes.getValueAt(selectedRow, 0);

            if (idObj != null) {
                try {
                    Long id = Long.valueOf(String.valueOf(idObj));

                    DocenteService docenteService = new DocenteService();

                    if (docenteService.excluirDocente(id)) {

                        TBDocentes.removeRow(selectedRow);

                        JOptionPane.showMessageDialog(null, "O Docente foi excluído com sucesso na base de dados");
                    } else {
                        JOptionPane.showMessageDialog(null, "Docente com ID " + id + " não foi encontrado na base de dados");
                    }
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(null, "Erro ao converter o ID para Long. Verifique o formato do ID, por favor.");
                }
            } else {
                JOptionPane.showMessageDialog(null, "ID é nulo. Verifique a linha selecionada, por favor.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Por favor, selecione uma linha para excluir.");
        }
       popularTabela();
    }//GEN-LAST:event_btnExcluirActionPerformed

   
    
    private void jComboBox1AncestorAdded(javax.swing.event.AncestorEvent evt) {
        CadeiraController cadeiraController = new CadeiraController();
        cadeiraController.exibirCadeira(ComboBoxCadeiras);
    }

    private void preencherComboBoxNivel() {
        
    ComBoxNivelAcesso.removeAllItems();
   for( Role role: Role.values()){
    ComBoxNivelAcesso.addItem(role);
   }
}

    private void salvarDocente() {

        String nome = TextNome.getText();
        String endereco = TextEndereco.getText();
        String email = TextEmail.getText();
        String telefone = TextTelefone.getText();
        String especializacao = TxtEspecializacao.getText();
        String experienciaTexto = textExperiencia.getText();
        int experiencia = Integer.parseInt(experienciaTexto);
        Role nivelAcesso = (Role) ComBoxNivelAcesso.getSelectedItem();
        Cadeira nomeCadeira = (Cadeira) ComboBoxCadeiras.getSelectedItem();

        if (nome.isEmpty() || endereco.isEmpty() || email.isEmpty()
                || telefone.isEmpty() || especializacao.isEmpty() || nomeCadeira == null || nivelAcesso == null) {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos obrigatórios.");
            return;
        }

        String senhaGerada = GeradorSenha.generateRandomSenha();

        //Usuario
        User usuario = new User();
        usuario.setEmail(email);
        usuario.setSenha(senhaGerada);
        usuario.setNivelAcesso(nivelAcesso);

        //Docente
        Docente novoDocente = new Docente();
        novoDocente.setNome(nome);
        novoDocente.setEndereco(endereco);
        novoDocente.setEmail(email);
        novoDocente.setTelefone(telefone);
        novoDocente.setEspecializacao(especializacao);
        novoDocente.setExperiencia(experiencia);
        novoDocente.setCadeira(nomeCadeira);
        novoDocente.setUsuario(usuario);

        DocenteController docenteController = new DocenteController();

        docenteController.cadastrarDocenteComUsuario(novoDocente, usuario);

        limparCampos();
        popularTabela();
    }

    private Docente carregarDadosParaEdicao(Long id) {
        DocenteService docenteService = new DocenteService();
        Docente docente = docenteService.buscarDocente(id);

    if (docente != null) {
        TextNome.setText(docente.getNome());
        TxtEspecializacao.setText(docente.getEspecializacao());
        textExperiencia.setText(String.valueOf(docente.getExperiencia()));
        TextEndereco.setText(docente.getEndereco());
        TextTelefone.setText(String.valueOf(docente.getTelefone()));
        TextEmail.setText(docente.getEmail());

       
        Cadeira cadeiraAssociada = docente.getCadeira();
        if (cadeiraAssociada != null) {
            ComboBoxCadeiras.setSelectedItem(cadeiraAssociada);
        }

        return docente;
    } else {
        JOptionPane.showMessageDialog(null, "Docente com ID " + id + " não foi encontrado na base de dados");
        return null;
    }
    }
    
   

    private void limparCampos() {
        TextNome.setText("");
        TextEndereco.setText("");
        TextEmail.setText("");
        TextTelefone.setText("");
        TxtEspecializacao.setText("");
        textExperiencia.setText("");
    }

   private void salvarAlteracoes(Long id) {
    EntityManager em = Connection.getEntityManager();
    try {
        DocenteService docenteService = new DocenteService(em);
        Docente docente = docenteService.buscarDocente(id);

        if (docente != null) {
            docente.setNome(TextNome.getText());
            docente.setEspecializacao(TxtEspecializacao.getText());
            docente.setExperiencia(Integer.parseInt(textExperiencia.getText()));
            docente.setEndereco(TextEndereco.getText());
            docente.setEmail(TextEmail.getText());
            docente.setTelefone(TextTelefone.getText());
            Cadeira cadeiraSelecionada = (Cadeira) ComboBoxCadeiras.getSelectedItem();
            docente.setCadeira(cadeiraSelecionada);

            boolean sucesso = docenteService.updateDocente(docente);

            if (sucesso) {
                JOptionPane.showMessageDialog(null, "Alterações salvas com sucesso!");
            } else {
                JOptionPane.showMessageDialog(null, "Erro ao salvar as alterações. Verifique o console para mais detalhes.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Docente com ID " + id + " não foi encontrado na base de dados");
        }
    } finally {
        if (em != null && em.isOpen()) {
            em.close();
        }
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Role> ComBoxNivelAcesso;
    private javax.swing.JComboBox<Cadeira> ComboBoxCadeiras;
    private javax.swing.JTable TabelaDocentes;
    private javax.swing.JTextField TextEmail;
    private javax.swing.JTextField TextEndereco;
    private javax.swing.JTextField TextNome;
    private javax.swing.JTextField TextTelefone;
    private javax.swing.JTextField TxtEspecializacao;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JToggleButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelCD;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField textExperiencia;
    // End of variables declaration//GEN-END:variables
}
