/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import javax.swing.JOptionPane;

/**
 *
 * @author Carla Morais
 */
public class ViewMenuPrincipalDocente extends javax.swing.JFrame {

    /**
     * Creates new form ViewMenuPrincipal
     */
    public ViewMenuPrincipalDocente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktop1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PanelAulasHoje = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        PanelHorario = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        Sair = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        MenuDocente = new javax.swing.JMenu();
        MenuCadeira = new javax.swing.JMenu();
        MenuSala = new javax.swing.JMenuItem();
        MenuMarcacaoAula = new javax.swing.JMenuItem();
        MenuHorario = new javax.swing.JMenuItem();
        MenuCurso = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktop1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 204, 255));
        jLabel1.setText("Seja Bem-Vindo, Docente");

        jPanel2.setBackground(new java.awt.Color(153, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Aulas Hoje");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(293, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PanelAulasHojeLayout = new javax.swing.GroupLayout(PanelAulasHoje);
        PanelAulasHoje.setLayout(PanelAulasHojeLayout);
        PanelAulasHojeLayout.setHorizontalGroup(
            PanelAulasHojeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PanelAulasHojeLayout.setVerticalGroup(
            PanelAulasHojeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAulasHojeLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 236, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(153, 255, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Horário");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel3)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jButton1.setText("Visualizar horário Semanal");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Visualizar  horário Mensal");

        javax.swing.GroupLayout PanelHorarioLayout = new javax.swing.GroupLayout(PanelHorario);
        PanelHorario.setLayout(PanelHorarioLayout);
        PanelHorarioLayout.setHorizontalGroup(
            PanelHorarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PanelHorarioLayout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(PanelHorarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        PanelHorarioLayout.setVerticalGroup(
            PanelHorarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelHorarioLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
        );

        javax.swing.GroupLayout jDesktop1Layout = new javax.swing.GroupLayout(jDesktop1);
        jDesktop1.setLayout(jDesktop1Layout);
        jDesktop1Layout.setHorizontalGroup(
            jDesktop1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktop1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jDesktop1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktop1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jDesktop1Layout.createSequentialGroup()
                        .addGap(0, 50, Short.MAX_VALUE)
                        .addComponent(PanelAulasHoje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86)
                        .addComponent(PanelHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(116, 116, 116))))
        );
        jDesktop1Layout.setVerticalGroup(
            jDesktop1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktop1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(jDesktop1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PanelAulasHoje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(161, Short.MAX_VALUE))
        );

        Sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/imagens/home.png"))); // NOI18N
        Sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SairMouseClicked(evt);
            }
        });
        jMenuBar1.add(Sair);

        jMenu2.setText("Sistema");

        jMenu1.setText("Sair");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenu2.add(jMenu1);

        jMenu4.setText("Informações pessoais");
        jMenu2.add(jMenu4);

        jMenu5.setText("Mudar Senha");
        jMenu2.add(jMenu5);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Cadastro");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        MenuDocente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/imagens/teacher.png"))); // NOI18N
        MenuDocente.setText("Docente");
        MenuDocente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuDocenteMouseClicked(evt);
            }
        });
        MenuDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuDocenteActionPerformed(evt);
            }
        });
        jMenu3.add(MenuDocente);

        MenuCadeira.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/imagens/books.png"))); // NOI18N
        MenuCadeira.setText("Cadeira");
        MenuCadeira.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuCadeiraMouseClicked(evt);
            }
        });
        MenuCadeira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCadeiraActionPerformed(evt);
            }
        });
        jMenu3.add(MenuCadeira);

        MenuSala.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/imagens/school-desk.png"))); // NOI18N
        MenuSala.setText("Sala");
        MenuSala.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuSalaMouseClicked(evt);
            }
        });
        MenuSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuSalaActionPerformed(evt);
            }
        });
        jMenu3.add(MenuSala);

        MenuMarcacaoAula.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/imagens/livro.png"))); // NOI18N
        MenuMarcacaoAula.setText("Agendamento de Aula");
        MenuMarcacaoAula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuMarcacaoAulaMouseClicked(evt);
            }
        });
        MenuMarcacaoAula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuMarcacaoAulaActionPerformed(evt);
            }
        });
        jMenu3.add(MenuMarcacaoAula);

        MenuHorario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/imagens/timetable.png"))); // NOI18N
        MenuHorario.setText("Horário");
        MenuHorario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuHorarioMouseClicked(evt);
            }
        });
        MenuHorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuHorarioActionPerformed(evt);
            }
        });
        jMenu3.add(MenuHorario);

        MenuCurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/imagens/graduacao.png"))); // NOI18N
        MenuCurso.setText("Curso");
        MenuCurso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuCursoMouseClicked(evt);
            }
        });
        MenuCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCursoActionPerformed(evt);
            }
        });
        jMenu3.add(MenuCurso);

        jMenuBar1.add(jMenu3);

        jMenu6.setText("Sobre");
        jMenu6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu6MouseClicked(evt);
            }
        });
        jMenu6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu6ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktop1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktop1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MenuMarcacaoAulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuMarcacaoAulaActionPerformed
        jDesktop1.removeAll();
        ViewCadastroAula aula = new ViewCadastroAula();
        jDesktop1.add(aula).setVisible(true);
    }//GEN-LAST:event_MenuMarcacaoAulaActionPerformed

    private void MenuDocenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuDocenteMouseClicked
      jDesktop1.removeAll();
        ViewCadastroDocente docente = new    ViewCadastroDocente();
         jDesktop1.add(docente).setVisible(true);
    }//GEN-LAST:event_MenuDocenteMouseClicked

    private void SairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SairMouseClicked
        int opcao = JOptionPane.showConfirmDialog(null, "Deseja realmente sair?", "Confirmação", JOptionPane.YES_NO_OPTION);
    
    if (opcao == JOptionPane.YES_OPTION) {
        Login login = new Login();
        login.setVisible(true);
        dispose();

    }
    }//GEN-LAST:event_SairMouseClicked

    private void MenuCadeiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCadeiraActionPerformed
        jDesktop1.removeAll();
        ViewCadastroCadeira cadeira = new ViewCadastroCadeira();

        jDesktop1.add(cadeira).setVisible(true);
    }//GEN-LAST:event_MenuCadeiraActionPerformed

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu3MouseClicked

    private void MenuCadeiraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuCadeiraMouseClicked
        // TODO add your handling code here:
        jDesktop1.removeAll();
        ViewCadastroCadeira cadeira = new ViewCadastroCadeira();

        jDesktop1.add(cadeira).setVisible(true);
    }//GEN-LAST:event_MenuCadeiraMouseClicked

    private void MenuCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuCursoActionPerformed

    private void MenuDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuDocenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuDocenteActionPerformed

    private void MenuCursoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuCursoMouseClicked
       jDesktop1.removeAll();
        ViewCadastroCurso curso = new ViewCadastroCurso();

        jDesktop1.add(curso).setVisible(true);
    }//GEN-LAST:event_MenuCursoMouseClicked

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void MenuMarcacaoAulaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuMarcacaoAulaMouseClicked
        // TODO add your handling code here:
        

    }//GEN-LAST:event_MenuMarcacaoAulaMouseClicked

    private void MenuHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuHorarioActionPerformed
        // TODO add your handling code here:
         jDesktop1.removeAll();
        ViewCadastroHorario horario = new ViewCadastroHorario();
        jDesktop1.add(horario).setVisible(true);
    }//GEN-LAST:event_MenuHorarioActionPerformed

    private void MenuHorarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuHorarioMouseClicked
        jDesktop1.removeAll();
        ViewCadastroHorario horario = new ViewCadastroHorario();
        jDesktop1.add(horario).setVisible(true);
    }//GEN-LAST:event_MenuHorarioMouseClicked

    private void MenuSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuSalaActionPerformed
        // TODO add your handling code here:
        jDesktop1.removeAll();
        ViewCadastradoSaladeAula sala = new ViewCadastradoSaladeAula();

        jDesktop1.add(sala).setVisible(true);
    }//GEN-LAST:event_MenuSalaActionPerformed

    private void MenuSalaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuSalaMouseClicked
        // TODO add your handling code here:
        jDesktop1.removeAll();
        ViewCadastradoSaladeAula sala = new ViewCadastradoSaladeAula();

        jDesktop1.add(sala).setVisible(true);
    }//GEN-LAST:event_MenuSalaMouseClicked

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenu6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu6MouseClicked
        // TODO add your handling code here:
         jDesktop1.removeAll();
        ViewSobre sobre = new ViewSobre();
        jDesktop1.add(sobre).setVisible(true);
    }//GEN-LAST:event_jMenu6MouseClicked

    private void jMenu6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu6ActionPerformed
        // TODO add your handling code here:
         jDesktop1.removeAll();
        ViewSobre sobre = new ViewSobre();
        jDesktop1.add(sobre).setVisible(true);
    }//GEN-LAST:event_jMenu6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewMenuPrincipalDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewMenuPrincipalDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewMenuPrincipalDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewMenuPrincipalDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewMenuPrincipalDocente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuCadeira;
    private javax.swing.JMenu MenuCurso;
    private javax.swing.JMenu MenuDocente;
    private javax.swing.JMenuItem MenuHorario;
    private javax.swing.JMenuItem MenuMarcacaoAula;
    private javax.swing.JMenuItem MenuSala;
    private javax.swing.JPanel PanelAulasHoje;
    private javax.swing.JPanel PanelHorario;
    private javax.swing.JMenu Sair;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jDesktop1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    // End of variables declaration//GEN-END:variables
}
